/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OORestaurants;
import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;



/**
 *
 * @author user
 */
public class OO_Restaurants extends javax.swing.JFrame {

    /**
     * Creates new form OO_Restaurants
     */
    public OO_Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlblBurger = new javax.swing.JLabel();
        jtxtBurger = new javax.swing.JTextField();
        jlblTax4 = new javax.swing.JLabel();
        jlblPizza = new javax.swing.JLabel();
        jtxtPizza = new javax.swing.JTextField();
        jlblTilapia = new javax.swing.JLabel();
        jtxtTilapia = new javax.swing.JTextField();
        jlblFries = new javax.swing.JLabel();
        jtxtFries = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jlblCostOfMeal = new javax.swing.JLabel();
        jtxtCostOfMeal = new javax.swing.JTextField();
        jlblCostOfDrinks = new javax.swing.JLabel();
        jtxtCostOfDrinks = new javax.swing.JTextField();
        jlblTotalsofMD = new javax.swing.JLabel();
        jtxtTotalofMD = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jlblTax3 = new javax.swing.JLabel();
        jlblVanilla = new javax.swing.JLabel();
        jlblChocolate = new javax.swing.JLabel();
        jlblCapuccino = new javax.swing.JLabel();
        jlblSoda = new javax.swing.JLabel();
        jtxtSoda = new javax.swing.JTextField();
        jtxtCapuccino = new javax.swing.JTextField();
        jtxtChocolate = new javax.swing.JTextField();
        jtxtVanilla = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 8));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 500, 480));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 8));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Restaurant Management System");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Trademark.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 8));

        jlblBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblBurger.setText("Burger");

        jtxtBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBurgerActionPerformed(evt);
            }
        });

        jlblTax4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTax4.setText("Meals");

        jlblPizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblPizza.setText("Pizza");

        jtxtPizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPizzaActionPerformed(evt);
            }
        });

        jlblTilapia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTilapia.setText("Tilapia");

        jtxtTilapia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTilapia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTilapiaActionPerformed(evt);
            }
        });

        jlblFries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblFries.setText("Fries");

        jtxtFries.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jlblTax4)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblBurger)
                    .addComponent(jlblPizza)
                    .addComponent(jlblTilapia)
                    .addComponent(jlblFries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtBurger, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jtxtPizza, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jtxtTilapia)
                    .addComponent(jtxtFries))
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlblTax4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblBurger))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPizza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTilapia)
                    .addComponent(jtxtTilapia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblFries)
                    .addComponent(jtxtFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 380, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 8));

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTotal)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnExit)
                        .addComponent(jbtnReset)
                        .addComponent(jbtnReceipt)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 770, 70));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 8));

        jlblCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostOfMeal.setText("Cost Of Meal");

        jtxtCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCostOfMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostOfMealActionPerformed(evt);
            }
        });

        jlblCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostOfDrinks.setText("Cost Of Drinks");

        jtxtCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCostOfDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostOfDrinksActionPerformed(evt);
            }
        });

        jlblTotalsofMD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotalsofMD.setText("Total Cost of Items");

        jtxtTotalofMD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotalofMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalofMDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblTotalsofMD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTotalofMD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblCostOfMeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlblCostOfDrinks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jtxtCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfMeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotalofMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotalsofMD))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 380, 130));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 8));

        jlblTax3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTax3.setText("Drinks");

        jlblVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblVanilla.setText("Vanilla ");

        jlblChocolate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChocolate.setText("Chocolate");

        jlblCapuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCapuccino.setText("Capuccino");

        jlblSoda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSoda.setText("Soda");

        jtxtSoda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSodaActionPerformed(evt);
            }
        });

        jtxtCapuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCapuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCapuccinoActionPerformed(evt);
            }
        });

        jtxtChocolate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChocolateActionPerformed(evt);
            }
        });

        jtxtVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVanillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jlblTax3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblVanilla)
                    .addComponent(jlblChocolate)
                    .addComponent(jlblCapuccino)
                    .addComponent(jlblSoda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtVanilla)
                    .addComponent(jtxtChocolate)
                    .addComponent(jtxtCapuccino)
                    .addComponent(jtxtSoda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlblTax3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblVanilla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblChocolate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCapuccino)
                    .addComponent(jtxtCapuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSoda)
                    .addComponent(jtxtSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 380, 260));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 8));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("Tax");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("SubTotal");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jlblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jlblSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jlblTax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal))
                .addContainerGap())
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 380, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        SubClass_Child ItemCost = new SubClass_Child();        
        double iTax, iSubTotal, iTotal;
        
        ItemCost.Burger = ItemCost.pBurger * Double.parseDouble(jtxtBurger.getText());
        ItemCost.Pizza = ItemCost.pPizza * Double.parseDouble(jtxtPizza.getText());
        ItemCost.Tilapia = ItemCost.pTilapia * Double.parseDouble(jtxtTilapia.getText());
        ItemCost.Fries = ItemCost.pFries * Double.parseDouble(jtxtFries.getText());
        
        ItemCost.Vanilla = ItemCost.pVanilla * Double.parseDouble(jtxtVanilla.getText());
        ItemCost.Chocolate = ItemCost.pChocolate * Double.parseDouble(jtxtChocolate.getText());
        ItemCost.Capuccino = ItemCost.pCapuccino * Double.parseDouble(jtxtCapuccino.getText());
        ItemCost.Soda = ItemCost.pSoda * Double.parseDouble(jtxtSoda.getText());
        
        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        String SubTotal = String.format("$%.2f", iSubTotal);
        jtxtSubTotal.setText(SubTotal);
        
        String Tax = String.format("$%.2f", iTax);
        jtxtTax.setText(Tax);
        
        String Total = String.format("$%.2f", iTotal);        
        jtxtTotal.setText(Total);
        
        String Meals = String.format("$%.2f", ItemCost.Meals);
        jtxtCostOfMeal.setText(Meals);
        
        String Drinks = String.format("$%.2f", ItemCost.Drinks);
        jtxtCostOfDrinks.setText(Drinks);
        
        String TotalofMD = String.format("$%.2f", ItemCost.TotalofMD);
        jtxtTotalofMD.setText(TotalofMD);
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField cleartext = null;
              
        for (Component c:jPanel4.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
                                    
        for (Component c:jPanel6.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        
        for (Component c:jPanel7.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }    
        for (Component c:jPanel8.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }  
        
        jtxtReceipt.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBurgerActionPerformed

    private void jtxtCostOfMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostOfMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostOfMealActionPerformed

    private void jtxtCostOfDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostOfDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostOfDrinksActionPerformed

    private void jtxtTotalofMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalofMDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalofMDActionPerformed

    private void jtxtPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPizzaActionPerformed

    private void jtxtTilapiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTilapiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTilapiaActionPerformed

    private void jtxtFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFriesActionPerformed

    private void jtxtVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVanillaActionPerformed

    private void jtxtChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChocolateActionPerformed

    private void jtxtCapuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCapuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCapuccinoActionPerformed

    private void jtxtSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSodaActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        SubClass_Child iExit = new SubClass_Child();
        iExit.iExitSystem();
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        
        int refs = 1325 + (int) (Math.random()*4238);//issa random number generator
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        
        
                jtxtReceipt.append("\tRestaurant Management Systems:\n" +
                         "Reference:\t\t\t" + refs +                          
                "\n====================================\n" +
                        "Meals:\t\t" + jtxtCostOfMeal.getText() + "\n\n" +
                        "Drinks:\t\t" + jtxtCostOfDrinks.getText() + "\n\n" +
                        "Cost of Items:\t" + jtxtTotalofMD.getText() + "\n\n" +
                "=======================================" + "\n\n" +
                        "Tax:\t\t" + jtxtTax.getText() + "\n\n" +
                        "SubTotal:\t" + jtxtSubTotal.getText() + "\n\n" +
                        "Total:\t\t" + jtxtTotal.getText() + "\n" + 
                "=======================================" +
                        "\nDate: " + Tdate.format(timer.getTime()) + 
                        "\tTime: " + tTime.format(timer.getTime()) +
                        "\n\n\t\tThank you " );       
    
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JLabel jlblBurger;
    private javax.swing.JLabel jlblCapuccino;
    private javax.swing.JLabel jlblChocolate;
    private javax.swing.JLabel jlblCostOfDrinks;
    private javax.swing.JLabel jlblCostOfMeal;
    private javax.swing.JLabel jlblFries;
    private javax.swing.JLabel jlblPizza;
    private javax.swing.JLabel jlblSoda;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTax3;
    private javax.swing.JLabel jlblTax4;
    private javax.swing.JLabel jlblTilapia;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotalsofMD;
    private javax.swing.JLabel jlblVanilla;
    private javax.swing.JTextField jtxtBurger;
    private javax.swing.JTextField jtxtCapuccino;
    private javax.swing.JTextField jtxtChocolate;
    private javax.swing.JTextField jtxtCostOfDrinks;
    private javax.swing.JTextField jtxtCostOfMeal;
    private javax.swing.JTextField jtxtFries;
    private javax.swing.JTextField jtxtPizza;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSoda;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTilapia;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtTotalofMD;
    private javax.swing.JTextField jtxtVanilla;
    // End of variables declaration//GEN-END:variables
}
